// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cmikCpp
NumericVector cmikCpp(NumericVector bws, NumericVector N, NumericVector X, NumericVector Y, NumericVector kmax);
RcppExport SEXP migen_cmikCpp(SEXP bwsSEXP, SEXP NSEXP, SEXP XSEXP, SEXP YSEXP, SEXP kmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type bws(bwsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kmax(kmaxSEXP);
    __result = Rcpp::wrap(cmikCpp(bws, N, X, Y, kmax));
    return __result;
END_RCPP
}
// mmikCpp
NumericVector mmikCpp(List ctsLevels, NumericVector bws, NumericVector N, NumericVector cts, NumericVector Ni);
RcppExport SEXP migen_mmikCpp(SEXP ctsLevelsSEXP, SEXP bwsSEXP, SEXP NSEXP, SEXP ctsSEXP, SEXP NiSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type ctsLevels(ctsLevelsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bws(bwsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cts(ctsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Ni(NiSEXP);
    __result = Rcpp::wrap(mmikCpp(ctsLevels, bws, N, cts, Ni));
    return __result;
END_RCPP
}
