# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mmikCpp <- function(ctsLevels, bws, N, cts, Ni) {
    .Call('migen_mmikCpp', PACKAGE = 'migen', ctsLevels, bws, N, cts, Ni)
}

